In [ ]:
#Week_3
#NumPy
#Tip can run many functions in one cell save with # ie as comment and to run that only remove #and run

In [11]:
import numpy as np
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [13]:
data*=10
data

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [14]:
data+data

array([[ 30.,  -2.,  60.],
       [  0., -60., 130.]])

In [19]:
print(data.shape)  # (2, 3) -> 2 rows, 3 columns
print(data.ndim)   # 2 -> Number of dimensions
print(data.size)   # 6 -> Total number of elements
print(data.dtype)  # int64 (or int32 depending on your system)

(2, 3)
2
6
float64


In [20]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
print(arr2.shape)  # (2, 3) -> 2 rows, 3 columns
print(arr2.ndim)   # 2 -> Number of dimensions
print(arr2.size)   # 6 -> Total number of elements
print(arr2.dtype)  # int64 (or int32 depending on your system)

(2, 4)
2
8
int64


In [22]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.ndim)  # Output: 3 (3D array)


3


In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.empty((2,3,2)) #3d array empty returns arndom garbage values

array([[[1.88096321e-315, 0.00000000e+000],
        [1.01855798e-312, 9.54898106e-313],
        [1.08221785e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.10343781e-312],
        [1.08221785e-312, 9.76118064e-313],
        [1.08221785e-312, 1.90979621e-312]]])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.arange(3,15,3)

array([ 3,  6,  9, 12])

In [34]:
#astype
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [36]:
float_arr=arr.astype(np.float64)
float_arr
#float_arr.dtype

dtype('float64')

In [37]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [38]:
arr*arr #element by element multiplication

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
arr2=np.array([[0.,4.,1.],[4.,7.,2.]])
arr>arr2

array([[ True, False,  True],
       [False, False,  True]])

In [43]:
#basic indexing and slicing
arr=np.arange(10)
print(arr)
arr[5:8]

[0 1 2 3 4 5 6 7 8 9]


array([5, 6, 7])

In [45]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
#Boolean Indexing